./like_fourier 0
./like_fourier 1
./like_fourier 2
./like_fourier 3
./like_fourier 4
./like_fourier 5
./like_fourier 6
./like_fourier 7
./like_fourier 8
./like_fourier 9
./like_fourier 10
./like_fourier 11
./like_fourier 12
./like_fourier 13
./like_fourier 14
./like_fourier 15
./like_fourier 16
./like_fourier 17
./like_fourier 18
./like_fourier 19
./like_fourier 20
./like_fourier 21
./like_fourier 22
./like_fourier 23
./like_fourier 24
./like_fourier 25
./like_fourier 26
./like_fourier 27
./like_fourier 28
./like_fourier 29
./like_fourier 30
./like_fourier 31
./like_fourier 32
./like_fourier 33
./like_fourier 34
./like_fourier 35